name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cURL dependencies
      run: |
        sudo apt install libcurl4-openssl-dev libssl-dev
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint-fail-under
        shopt -s globstar
        pylint-fail-under --fail_under 9.9 ./**/*.py
